version: "3.9"
services:
  db:
    image: mongo:latest
  api:
    build: .
    image: image-gallery
    command: nodemon index
    ports:
      - "3000:3000"
    environment:
      - "DB=mongodb://db/image-gallery"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
  web:
    image: image-gallery
    command: npm start --prefix client
    ports:
      - "4200:4200"
    environment:
      - "REACT_APP_API_URL=http://localhost:3000"
    volumes:
      - ./client:/usr/src/app/client
      - /usr/src/app/client/node_modules
    depends_on:
      - api